---
api_key: "<%= ENV["HONEYBADGER_API_KEY"] %>"
env: "<%= Rails.env %>"
root: "<%= Rails.root.to_s %>"
development_environments:
- test
- development
- cucumber

debug: false

insights:
  enabled: <%= Rails.env.production? %>
